"""Initial Migration

Revision ID: 6b48b126f3d1
Revises: d36dd0c1703f
Create Date: 2020-11-06 03:09:36.826345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b48b126f3d1'
down_revision = 'd36dd0c1703f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('body', sa.Text(), nullable=True))
    op.drop_column('blogs', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'body')
    # ### end Alembic commands ###
